
set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)
# set(CMAKE_CXX_STANDARD ${GTBOT_CPP_STANDARD})

list(APPEND definitions
	$<$<CONFIG:Debug>:GOLXZN_DEBUG>
	_UNICODE UNICODE
)

add_compile_options(
	"$<$<C_COMPILER_ID:MSVC>:/utf-8>"
	"$<$<CXX_COMPILER_ID:MSVC>:/utf-8>"
)
